// This file is automatically generated. Do not modify it manually.
'use client';

import { useEffect, useState } from 'react';
import { onAuthStateChanged } from 'firebase/auth';
import { useAuth } from '@/firebase';
import type { AppUser, UserRole } from '@/types/auth';

export function useUser() {
  const auth = useAuth();
  const [user, setUser] = useState<AppUser | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, async (firebaseUser) => {
      if (firebaseUser) {
        try {
          const token = await firebaseUser.getIdTokenResult();
          const role = (token.claims.role as UserRole) || 'HUNTER';

          setUser({
            uid: firebaseUser.uid,
            email: firebaseUser.email,
            role: role,
            displayName: firebaseUser.displayName,
            photoURL: firebaseUser.photoURL,
          });
        } catch (error) {
          console.error('Error fetching custom claims:', error);
          // Handle error, maybe sign out user
          setUser(null);
        }
      } else {
        setUser(null);
      }
      setLoading(false);
    });

    return () => unsubscribe();
  }, [auth]);

  return { user, loading };
}
