// This file is automatically generated. Do not modify it manually.
'use client';

import { ReactNode } from 'react';
import { FirebaseProvider } from './provider';
import { firebaseApp } from './config';

export default function FirebaseClientProvider({ children }: { children: ReactNode }) {
  return <FirebaseProvider firebaseApp={firebaseApp}>{children}</FirebaseProvider>;
}
