
// This file is automatically generated. Do not modify it manually.
import { getApp, getApps, initializeApp, type FirebaseOptions } from 'firebase/app';
import { getAnalytics, isSupported, type Analytics } from 'firebase/analytics';

const firebaseConfigString = process.env.NEXT_PUBLIC_FIREBASE_CONFIG;

let firebaseConfig: FirebaseOptions;

if (!firebaseConfigString || firebaseConfigString === 'undefined') {
  console.warn("NEXT_PUBLIC_FIREBASE_CONFIG is not set. Using placeholder configuration. Please set up your Firebase project and configure the environment variable.");
  firebaseConfig = {
    apiKey: "placeholder",
    authDomain: "placeholder.firebaseapp.com",
    projectId: "placeholder",
    storageBucket: "placeholder.appspot.com",
    messagingSenderId: "placeholder",
    appId: "placeholder",
  };
} else {
  firebaseConfig = JSON.parse(firebaseConfigString);
}


// Initialize Firebase
const firebaseApp = getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();

// Initialize Analytics safely on the client
const analytics = typeof window !== 'undefined' ? isSupported().then(yes => yes ? getAnalytics(firebaseApp) : null) : null;

export { firebaseApp, firebaseConfig, analytics };
