
// This file is automatically generated. Do not modify it manually.
import { getApp, getApps, initializeApp, type FirebaseApp, type FirebaseOptions } from 'firebase/app';
import { getAnalytics, isSupported, type Analytics } from 'firebase/analytics';

const firebaseConfig: FirebaseOptions = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
};


// Conditional initialization to prevent app crash if keys are missing.
// The RootLayout will render a user-friendly error message in this case.
const isConfigValid = firebaseConfig.apiKey && firebaseConfig.apiKey !== 'placeholder';

const firebaseApp = isConfigValid
  ? (getApps().length === 0 ? initializeApp(firebaseConfig) : getApp())
  // Provide a dummy app object if config is invalid, to avoid import-time crashes.
  // The app will not function, but it will allow the layout to render its error message.
  : {} as FirebaseApp;

if (!isConfigValid) {
    console.warn("Firebase configuration is not fully set. The app will not function correctly. Please provide NEXT_PUBLIC_ environment variables.");
}

// Initialize Analytics safely on the client
const analytics = isConfigValid && typeof window !== 'undefined'
    ? isSupported().then(yes => yes ? getAnalytics(firebaseApp) : null)
    : null;

export { firebaseApp, firebaseConfig, analytics };
