// This file is automatically generated. Do not modify it manually.
'use client';
import { createContext, useContext, useMemo, type ReactNode } from 'react';
import { getAuth, type Auth } from 'firebase/auth';
import { getFirestore, type Firestore } from 'firebase/firestore';
import { FirebaseApp } from 'firebase/app';
import { firebaseApp } from './config';

export interface FirebaseContextValue {
  auth: Auth;
  firestore: Firestore;
  firebaseApp: FirebaseApp;
}

const FirebaseContext = createContext<FirebaseContextValue | null>(null);

export interface FirebaseProviderProps {
  children: ReactNode;
  firebaseApp: FirebaseApp;
}

export function FirebaseProvider({ children, firebaseApp }: FirebaseProviderProps) {
  const auth = getAuth(firebaseApp);
  const firestore = getFirestore(firebaseApp);

  const value = useMemo(
    () => ({
      auth,
      firestore,
      firebaseApp,
    }),
    [auth, firestore, firebaseApp],
  );

  return <FirebaseContext.Provider value={value}>{children}</FirebaseContext.Provider>;
}

export const useFirebase = () => {
  const context = useContext(FirebaseContext);
  if (!context) {
    throw new Error('useFirebase must be used within a FirebaseProvider');
  }
  return context;
};

export const useFirebaseApp = () => useFirebase().firebaseApp;
export const useFirestore = () => useFirebase().firestore;
export const useAuth = () => useFirebase().auth;
