export type DocumentStatus = 'PENDING' | 'VERIFIED' | 'REJECTED' | 'EXPIRED';
export type DocumentType = 'OUTFITTER_PERMIT' | 'PH_LICENSE' | 'LIABILITY_DISCLAIMER';

export interface OutfitterDocument {
  id?: string; // Auto-generated by Firestore
  outfitterId: string;
  type: DocumentType;
  
  // File Details
  fileName: string;
  fileUrl: string; // The secure link from Firebase Storage
  fileSize: number; // In bytes
  
  // Verification State
  status: DocumentStatus;
  uploadedAt: Date; // Firebase Timestamp
  expiryDate: Date | null; // Crucial for legal operating permits
  
  // Admin Audit Trail
  verifiedAt?: Date; // Timestamp of when you approved it
  verifiedBy?: string; // Admin ID
  rejectionReason?: string; // e.g., "Image too blurry" or "Expired"
}